"""empty message

Revision ID: 4b98cec16aa7
Revises: 4fe81e8e41c1
Create Date: 2018-04-13 15:27:31.688066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b98cec16aa7'
down_revision = '4fe81e8e41c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examiner_module',
    sa.Column('examiner_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['examiner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examiner_module')
    # ### end Alembic commands ###
