"""empty message

Revision ID: 9ec66d75dbd1
Revises: 97ce1476c11d
Create Date: 2018-04-17 11:06:11.652708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec66d75dbd1'
down_revision = '97ce1476c11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('card_number', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_card_number'), 'user', ['card_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_card_number'), table_name='user')
    op.drop_column('user', 'card_number')
    # ### end Alembic commands ###
