"""empty message

Revision ID: a66fe27e8651
Revises: e4818770e58c
Create Date: 2018-05-25 13:59:26.449035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66fe27e8651'
down_revision = 'e4818770e58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_scale', sa.Column('scale_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_scale', 'scale_id')
    # ### end Alembic commands ###
