"""empty message

Revision ID: ab65ed3bb62c
Revises: c76602335831
Create Date: 2018-06-01 14:08:38.602795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab65ed3bb62c'
down_revision = 'c76602335831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_result', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_result', 'date')
    # ### end Alembic commands ###
